name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Installs Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs global packages
        run: npm i -g eslint
      - name: Installs packages
        run: npm i
      - name: Lints the repository
        run: eslint src --ext .ts --fix